function Xdot = func_orbit_inertial_static_SB_faraway( ...
    t, X, ...
    mu_SB,mu_Sun, ...
    this_SB_pos,this_Sun_pos, ...
    this_force,this_disturbance,this_SC_mass)

% SC Position
R_SC = X(1:3);

% SB Position
R_SC_SB = R_SC - this_SB_pos;
distance_SC_SB = norm(R_SC_SB);

% Sun Position
R_SC_Sun = R_SC - this_Sun_pos;
distance_SC_Sun = norm(R_SC_Sun);

acc = ...
- mu_SB  * R_SC_SB(1:3)  / distance_SC_SB^3 ...
- mu_Sun * R_SC_Sun(1:3) / distance_SC_Sun^3 ...
+ 1e-3 * this_force(1:3) / this_SC_mass ...
+ 1e-3 * this_disturbance(1:3) / this_SC_mass;

Xdot=[X(4:6); acc];

end
