function plot_spacecraft_components_DARE(true_SC)

    plot_colors = func_get_plot_colors();
    
    % Body shapes
    for i_shape = 1:length(true_SC.true_SC_body.shape_model)
        shape_i = true_SC.true_SC_body.shape_model{i_shape};
        if isfield(shape_i, 'color')
            color = shape_i.color;
        else
            color = 'white';
        end
        if isfield(shape_i, 'name') && shape_i.name ~= ""
            name = shape_i.name;
            handle_vis = 'on';
        else
            name = 'Body';
            handle_vis = 'off';
        end
        trisurf( ...
            shape_i.Faces, ...
            shape_i.Vertices(:, 1), ...
            shape_i.Vertices(:, 2), ...
            shape_i.Vertices(:, 3), ...
            'FaceColor', color, 'DisplayName', name, 'HandleVisibility', handle_vis)
        hold on
    end
    
    % Solar panels
    for sp = 1:true_SC.true_SC_solar_panel.num_solar_panels
        shape_i = true_SC.true_SC_solar_panel.solar_panel_data(sp).shape_model;
        trisurf( ...
            shape_i.Faces, ...
            shape_i.Vertices(:, 1), ...
            shape_i.Vertices(:, 2), ...
            shape_i.Vertices(:, 3), ...
            'FaceColor', 'blue', "DisplayName", ['Solar Panel ', num2str(sp)])
    end
    
    i_count = 1;
    
    % Micro thrusters
    if true_SC.true_SC_body.flag_hardware_exists.adc_micro_thruster == 1
        for i = 1:true_SC.true_SC_micro_thruster_actuator.num_micro_thruster
            MT_data_i = true_SC.true_SC_micro_thruster_actuator.MT_data(i);
            quiver3( ...
                MT_data_i.location(1), ...
                MT_data_i.location(2), ...
                MT_data_i.location(3), ...
                MT_data_i.orientation(1), ...
                MT_data_i.orientation(2), ...
                MT_data_i.orientation(3), ...
                'color', plot_colors{i_count}, "LineWidth", 3, 'HandleVisibility', 'off', "AutoScaleFactor", 0.1)
        end
        name = 'Micro Thrusters';
        quiver3([], [], [], [], [], [], ...
            'color', plot_colors{i_count}, "LineWidth", 3, "DisplayName", name, "AutoScaleFactor", 0.1);
        i_count = i_count + 1;
    end
    
    % Chemical thrusters
    if true_SC.true_SC_body.flag_hardware_exists.navigation_chemical_thruster == 1
        n_ct = true_SC.true_SC_chemical_thruster_actuator.num_chemical_thruster;
        for i = 1:n_ct
            ct_data_i = true_SC.true_SC_chemical_thruster_actuator.chemical_thruster_data(i);
            color = plot_colors{2};
            scale = 0.25;
            quiver3( ...
                ct_data_i.location(1), ...
                ct_data_i.location(2), ...
                ct_data_i.location(3), ...
                -ct_data_i.orientation(1), ...
                -ct_data_i.orientation(2), ...
                -ct_data_i.orientation(3), ...
                'color', color, "LineWidth", 4, 'HandleVisibility','off', "AutoScaleFactor", scale)
        end
    end
    
end